### ISSUE TITLE
feat: Room titles

### ISSUE THREAD

**Issue by YohannesTz** [RobiMez/sma#13]
Weird strings are hard to differentiate. especially when you have two SMA's opened.

**Comment by RobiMez** [comment]
ill add an option to customize your room title as long as its not taken

**Comment by YohannesTz** [comment]
why? what if you wanna host an event twice? like with the same title?

**Comment by RobiMez** [comment]
> why? what if you wanna host an event twice? like with the same title?

hmm , aliasing then i guess

**Comment by RobiMez** [comment]
Fixed by #23
